version: '3'

services:
  app:
    container_name: app
    build: .
    volumes:
    - ./:/var/www
    depends_on:
      - app-mysql
      - app-redis

  app-mysql:
    container_name: app_mysql
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
    - "3306"
    volumes:
    - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root

  app-redis:
    container_name: app_redis
    image: redis:alpine
    expose:
      - 6379

  app-nginx:
    container_name: app_nginx
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
